### PR TITLE
feat(schema): Add rdau:P60537 (medium of performance) field

### LINKED ISSUE #42: Controlled vocabulary for instrumentation ("medium of performance")
**Issue:** TROMPA users will need to be able to filter musical scores according to their medium of performance, that is, the instrumental parts that comprise the score. 

**Currently** this metadata is associated with a score as a textual string via dc:subject. This is problematic for several reasons:

1. consistency is important if this information is going to be used for search and filtering, thus a closed vocabulary is preferable
2. to support searching and filtering in multiple languages, we would currently have to associate several "subjects" with a score, each in a different language (e.g. "piano" vs. "klavier")
3. dc:subject is a semantically very broad predicate to refer to instrumentation specifically.

**Proposal**:  We should incorporate a closed vocabulary of instrumentation terms into the CE. A comprehensive taxonomy exists in the Library of Congress's Medium of Performance Thesaurus for Music: http://id.loc.gov/authorities/performanceMediums.html.

The taxonomy could be imported into the CE, using individual nodes for each type of instrument / ensemble. These can then be associated with language labels in the various languages we support, ensuring that "klavier" and "piano" can both return scores associated with the same "piano" node. N.b. that the taxonomy is only supplied with English language labels; we would have to supply our own translations (potentially limited to those instrument / ensemble terms we expect to be most widely searched for). 

In addition to the (very broad) dc:subject, the association between a score and a performance medium could be more precisely (semantically) specified by borrowing the RDA Unconstrained element set's [`rdau:P60537`](http://www.rdaregistry.info/Elements/u/#P60537) ("has medium of performance of musical content") property (or translating to it when exporting the graphql relationship via the REST wrapper).

### PR DESCRIPTION
**Pull request by alastair**
Fixes #42

Useful in MusicComposition and MediaObject to indicate instrumentation

As discussed in this issue, and in slack recently.

Need confirmation that this is correct in the context:
`"rdau": "http://rdaregistry.info/Elements/u/"`

We decided to use library of congress performance mediums, but this patch doesn't verify that the value of the field is a URL. If we want to add this we should modify `additionalTypeFieldTransformer` to be a generic is-a-url transformer checker.

Example mutation:
```graphql
mutation {
  CreateMusicComposition(
        name: "Prelude number 1 in some key"
        contributor: "https://musicbrainz.org"
        creator: "https://github.com/trompamusic/ce-data-import"
        source: "https://musicbrainz.org/work/some-uuid"
        format: "text/html"
    mediumOfPerformance:["http://id.loc.gov/authorities/performanceMediums/mp2013015550"]
) {
identifier
}
}
```

resulting json-ld output (edited)
```json
{
  "@context": [
    "https://schema.org/",
    {
      "dc": "http://purl.org/dc/terms/",
      "prov": "http://www.w3.org/ns/prov#",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "bib": "https://bib.schema.org/",
      "rdau": "http://rdaregistry.info/Elements/u/"
    }
  ],
  "@type": [
    "https://schema.org/MusicComposition"
  ],
  ... lots of items chopped here
  "rdau:P60537": [
    "http://id.loc.gov/authorities/performanceMediums/mp2013015550"
  ],
  "firstPerformance": null,
  "bitrate": null,
  "dc:language": null,
  "dc:source": "https://musicbrainz.org/work/some-uuid",
  ... lots of items chopped here
  "dc:identifier": "5a5f683f-ebe4-4ee0-975e-21170b44f6d6",
  "identifier": "5a5f683f-ebe4-4ee0-975e-21170b44f6d6",
  "image": null,
  "schema_publisher": [],
  "workExampleMediaObject": [],
  "dc:created": "2021-04-05T15:21:55.292000000Z",
  "dc:format": "text/html",
  ... lots of items chopped here
  "name": "Prelude number 1 in some key",
  ... lots of items chopped here
  "dc:contributor": "https://musicbrainz.org",
  "contributor": "https://musicbrainz.org",
  ... lots of items chopped here
}
```

### CODE REVIEW

**Comment by musicog** [comment]
Almost perfect :-)

The JSON-LD output needs to produce `{"@id": "http://example.org/foo"}` objects for external URIs, instead of just `"http://example.org/foo"`, which is otherwise interpreted as a string literal.

**Comment by alastair** [comment]
The correct output of this field should be:
```json
"rdau:P60537": [
    {"@id": "http://id.loc.gov/authorities/performanceMediums/mp2013015550"}
]
```

We're going to need a way that indicates to the json-ld serialiser that some fields are IDs instead of string constants. This could be added to the json schema definition file. If we do this then it makes sense that we also validate that the field is a URL, because to be an ID it always must be an external url.

**Comment by alastair** [comment]
I updated this to add a `relationalProperties` field to the json definition file that indicates when a field should be rendered as a reference to an external url instead of a string.

I also updated the additionalProperties transformer to turn it into a generic "check is a url" transformer and added the mediumOfPerformance field

**Comment by alastair** [comment]
@ChristiaanScheermeijer ready for review

**Review by ChristiaanScheermeijer — APPROVED** [review]
LGTM

**Pull request merged**
