### PR TITLE
feat(project): remove a lot of redundant code after neo4j-graphql-js …

### PR DESCRIPTION
**Pull request by ChristiaanScheermeijer**
@alastair @musicog @VincentCouzij 

This is a big one ... sorry about that :-)

I've managed to "solve" the interface problem in the neo4j-graphql-js library. Although this is still a PR, I've experimented with this and which code becomes redundant.

Also, since neo4j-graphql-js has introduced an auto-generated filter argument for each query, a few custom queries can be removed as well.

btw filters also support relational filtering:

```
query {
  ControlAction(filter: { target: { identifier: "" } }) {
    identifier
  }
}
```

Last but not least, every type now has its own unique relational mutation queries. So no more `AddThingInterfaceThingInterface` but `AddDigitalDocumentAudio` and `MergeDigitalDocumentAudio`. Merge is prefered as this does not create duplicate relations if it already exists.

The only problem is that this change is definitely NOT backwards compatible.

### CODE REVIEW

**Comment by ChristiaanScheermeijer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ src/resolvers/query.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/trompamusic/ce-api/pullRequest?prid=4791347&bid=15952488)

**Comment by alastair** [comment]
Backwards compatibility isn't a problem. I like the idea of more explicit join mutations.
Thanks for doing this, I'll try and look at it early next week, if I have any questions perhaps we can talk about them on the 20th.

**Comment by ChristiaanScheermeijer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ src/resolvers/query.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/trompamusic/ce-api/pullRequest?prid=4791347&bid=15952488)

**Comment by ChristiaanScheermeijer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ src/resolvers/query.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/trompamusic/ce-api/pullRequest?prid=4791347&bid=15952488)

**Comment by ChristiaanScheermeijer** [comment]
The PR in the neo4j-graphql-js library has been merged! 🎉  Now we need to wait until a new version has been released so we can use the fix in this PR.

**Comment by alastair** [comment]
Great work on the PR in the graphql library! I'm currently modifying our importer to use these new mutations. The Merge mutation is great, I have a bunch of code which first checks for a relationship before adding it. I can simplify this code. I'll let you know later today when I have the client updated against this code.
Will you wait for a new version of neo4j-graphql-js to be released before you merge this?

**Comment by ChristiaanScheermeijer** [comment]
Hi @alastair, thanks! I've just "embedded" the fix in the repository so we can continue without having to wait... I'm ready to merge this PR now 😃

**Comment by ChristiaanScheermeijer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ src/resolvers/query.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/trompamusic/ce-api/pullRequest?prid=4791347&bid=15952488)

**Comment by alastair** [comment]
I'm looking at this now.

How do I add a person as the composer of a MusicComposition?
On the current api-test.trompamusic.eu I see a mutation `AddCreativeWorkInterfaceAuthor`, however I don't see this mutation when I build this branch. Interestingly, I do see `AddMusicCompositionLyricist`, so there are _some_ relations, but not all of the ones I expect to see.
Are there any additional steps that I need to run to "compile" the schema?

**Comment by alastair** [comment]
Ah, never mind - I just noticed that this has been merged into staging and some other commits made since then. I didn't see the merge notification on this page.
I can now see the mutation when running the staging branch.

**Comment by alastair** [comment]
I seem to have an issue with the following mutation:
```
mutation {
  AddDigitalDocumentExampleOfWork(from: {identifier:"d68e79db-1f76-4a54-9357-a7d892686e69"} 
    to: {identifier:"b12d4087-4fb2-4177-a4c9-d9750c0dfbab"}) {
    from {
      ... on DigitalDocument {
        identifier
      }
    }
    to {
      ... on CreativeWork {
        identifier
      }
    }
  }
}
```
The error message:
```
{
  "errors": [
    {
      "message": "Abstract type CreativeWorkInterface must resolve to an Object type at runtime for field _AddDigitalDocumentExampleOfWorkPayload.to with value { identifier: \"b12d4087-4fb2-4177-a4c9-d9750c0dfbab\" }, received \"undefined\". Either the CreativeWorkInterface type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
      "locations": [
        {
          "line": 8,
          "column": 5
        }
      ],
      "path": [
        "AddDigitalDocumentExampleOfWork",
        "to"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Abstract type CreativeWorkInterface must resolve to an Object type at runtime for field _AddDigitalDocumentExampleOfWorkPayload.to with value { identifier: \"b12d4087-4fb2-4177-a4c9-d9750c0dfbab\" }, received \"undefined\". Either the CreativeWorkInterface type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
          "locations": [
            {
              "line": 8,
              "column": 5
            }
          ],
          "stacktrace": [
            "GraphQLError: Abstract type CreativeWorkInterface must resolve to an Object type at runtime for field _AddDigitalDocumentExampleOfWorkPayload.to with value { identifier: \"b12d4087-4fb2-4177-a4c9-d9750c0dfbab\" }, received \"undefined\". Either the CreativeWorkInterface type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
            "    at ensureValidRuntimeType (/app/node_modules/graphql/execution/execute.js:667:11)",
            "    at completeAbstractValue (/app/node_modules/graphql/execution/execute.js:660:42)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:585:12)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)",
            "    at /app/node_modules/graphql/execution/execute.js:492:16"
          ]
        }
      }
    }
  ],
  "data": {
    "AddDigitalDocumentExampleOfWork": {
      "from": {
        "identifier": "d68e79db-1f76-4a54-9357-a7d892686e69"
      },
      "to": null
    }
  }
}

```

**Comment by ChristiaanScheermeijer** [comment]
Does the ExampleOfWork node exist? I get the following error when searching for the id: 

https://api-test.trompamusic.eu/b12d4087-4fb2-4177-a4c9-d9750c0dfbab

**Comment by alastair** [comment]
sorry, this is in my local environment.
I notice that the relation _does_ exist, so it seems like it gets created but then fails to return the correct data:

Screenshot 2020-01-14 at 3 09 53 PM

There appears to be an additional problem where a second Composition node is getting created. I'll try and reproduce the issue.

**Comment by ChristiaanScheermeijer** [comment]
Ah I see, did the DigitalDocument already exist before the update? If so, you've probably run into the same problem that happened in the test environment. Not all nodes have the necessary labels to resolve interfaces to types.

You can see this by clicking on the DigitalDocument node and verify if you can see the following labels: 

image

**Comment by alastair** [comment]
I cleared the database before performing this upgrade, so it shouldn't have existed before-hand. I'll try and get some clear steps to reproduce this issue.

**Comment by ChristiaanScheermeijer** [comment]
Oh, that is strange indeed. That would be really helpful, as now I don't know why these labels aren't always added on creation 😕.

**Comment by ChristiaanScheermeijer** [comment]
I'm trying to reproduce on my local environment and have found that the following query does work:

```
mutation {
  MergeDigitalDocumentExampleOfWork(
    from: { identifier: "dcd69f90-a276-49be-b3c2-449a8d8e42ea"},
    to: { identifier:"1ff768d2-a456-42b6-85aa-88f8c8a679b6" }
  ) {
    from {
      identifier
    }
    to {
      identifier
    }
  }
}
```

When removing the fragments, the mutation will succeed.  I think this is caused by an issue I've just submitted a PR for in the neo4j-graphql-js library: https://github.com/neo4j-graphql/neo4j-graphql-js/pull/377

If the above PR gets merged, the mutation query that you are using should work again. 

I hope this solves your problem.

**Comment by alastair** [comment]
OK, I'll simplify these mutations to remove the fragment and let you know if I have any further issues

**Pull request merged**
